// NDepend issue suppressions for the whole solution (NDepend reads assembly-level
// SuppressMessage attributes from any analysed assembly, so this one file covers all projects).
//
// Keep this file short. Order of preference when NDepend reports something:
//   1. fix the code;
//   2. fix the rule or the JustMyCode definition in Stride.CommunityToolkit.ndproj
//      (generated code such as Stride.Core.DataSerializers and UpdateEngineAutoGenerated
//      is excluded there, not here);
//   3. only then add a targeted suppression below, with a real justification.
//
// Target format is "AssemblyName:CodeElementFullName" - the assembly prefix is mandatory,
// wildcards are not supported. A suppression silently does nothing once its target is gone,
// so prune entries when examples are removed.

using System.Diagnostics.CodeAnalysis;

// --- Naming: entry points of languages with their own conventions --------------------------
[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example01_Basic3DScene_FSharp:Program.main(String[])", Justification = "F# entry point is conventionally named 'main'.")]
[assembly: SuppressMessage("NDepend", "ND2007:MethodsNameShouldBeginWithAnUpperCharacter", Target = "Example05_PartialTorus_FSharp:Program.main(String[])", Justification = "F# entry point is conventionally named 'main'.")]
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Example01_Basic3DScene_VBasic:Example01_Basic3DScene_VBasic.Program.Main()", Justification = "VB.NET 'Main' next to the F# 'main' entry points: different language conventions, not inconsistent naming.")]

// --- DebugShapes: GPU/interop payload structs ---------------------------------------------
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Circle", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Quad", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Sphere", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.HalfSphere", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cube", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Capsule", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cylinder", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Cone", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Line", Scope = "field", Justification = "Interop/GPU payload - requires blittable sequential fields.")]
[assembly: SuppressMessage("NDepend", "ND1905:AFieldMustNotBeAssignedFromOutsideItsParentHierarchyTypes", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Primitives", Scope = "field", Justification = "Per-primitive vertex/index ranges filled by the mesh builders (SetupPrimitiveOffsets, BuildVertexData, BuildIndexData); plain data struct by design.")]

// --- Deliberate naming / API mirroring ---------------------------------------------------------
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Stride.CommunityToolkit.Bepu:Stride.CommunityToolkit.Bepu.SimulationExtensions", Scope = "deep", Justification = "RayCast/RayCastPenetrating mirror Stride.BepuPhysics.BepuSimulation's own casing; the Bullet wrapper mirrors Stride.Physics.Simulation.Raycast. Each wrapper matches its engine on purpose.")]
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Stride.CommunityToolkit.Bullet:Stride.CommunityToolkit.Bullet.SimulationExtensions", Scope = "deep", Justification = "Raycast/RaycastPenetrating mirror Stride.Physics.Simulation's own casing; the Bepu wrapper mirrors Stride.BepuPhysics.BepuSimulation.RayCast. Each wrapper matches its engine on purpose.")]
[assembly: SuppressMessage("NDepend", "ND3101:DontUseSystemRandomForSecurityPurposes", Target = "Stride.CommunityToolkit:Stride.CommunityToolkit.Helpers.VectorHelper", Scope = "deep", Justification = "Gameplay randomness (positions, directions); nothing security-related, and a seedable System.Random is the point.")]
// --- Constants that have to stay const ----------------------------------------------------------
// ND1804 warns that a public const is inlined into consumers, so a later value change does not reach
// them. These three are kept const on purpose; the other public constants became static readonly.
[assembly: SuppressMessage("NDepend", "ND1804:AvoidPubliclyVisibleConstantFields", Target = "Stride.CommunityToolkit:Stride.CommunityToolkit.Engine.CameraDefaults.MainCameraName", Justification = "Optional-parameter default of the Add*Camera and GetCameraEntity overloads, and C# requires a compile-time constant there. A consumer keeping the value it was compiled against still finds the camera it created with it.")]
[assembly: SuppressMessage("NDepend", "ND1804:AvoidPubliclyVisibleConstantFields", Target = "Stride.CommunityToolkit:Stride.CommunityToolkit.Engine.ScreenshotCapture.OutputPathVariable", Justification = "Environment-variable name, i.e. a contract with whoever launches the process; a consumer keeping the name it was compiled against is the correct behaviour.")]
[assembly: SuppressMessage("NDepend", "ND1804:AvoidPubliclyVisibleConstantFields", Target = "Stride.CommunityToolkit:Stride.CommunityToolkit.Engine.ScreenshotCapture.FrameVariable", Justification = "Environment-variable name, i.e. a contract with whoever launches the process; a consumer keeping the name it was compiled against is the correct behaviour.")]
[assembly: SuppressMessage("NDepend", "ND1805:FieldsShouldBeDeclaredAsPrivate", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.ImmediateDebugRenderObject", Scope = "deep", Justification = "instanceOffsets/primitivesToDraw(+NoDepth) are passed by ref into DebugPrimitiveRenderer.DrawPrimitives every frame; a property cannot be passed by ref, and copying the Primitives counter struct per draw would defeat the point of the ref.")]
// --- ImGui: deliberate design the rules cannot see ----------------------------------------------
// Public nested types kept nested: each is created by and scoped to its owner, and un-nesting
// would break the public API for a purely taxonomic gain.
[assembly: SuppressMessage("NDepend", "ND1306:NestedTypesShouldNotBeVisible", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiExtension+DisposableImGui", Justification = "Returned by the Begin* helpers and scoped to them.")]
[assembly: SuppressMessage("NDepend", "ND1306:NestedTypesShouldNotBeVisible", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiExtension+DisposableImGuiIndent", Justification = "Returned by UIndent and scoped to it.")]
[assembly: SuppressMessage("NDepend", "ND1306:NestedTypesShouldNotBeVisible", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.Inspector+Filter", Justification = "The member filter belongs to the Inspector that interprets it.")]
[assembly: SuppressMessage("NDepend", "ND1306:NestedTypesShouldNotBeVisible", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.Inspector+ValueHandler", Justification = "The handler signature belongs to the Inspector that invokes it.")]
[assembly: SuppressMessage("NDepend", "ND1306:NestedTypesShouldNotBeVisible", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor+PerfSampler", Justification = "Created by PerfMonitor.Sample and reads the monitor's private thread cache.")]
// Scope-guard structs disposed at the end of a using block; instances are never compared, sorted
// or used as keys, so the equality contract would be dead code.
[assembly: SuppressMessage("NDepend", "ND1313:OverrideEqualsAndOperatorEqualsOnValueTypes", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiExtension+DisposableImGui", Justification = "Scope guard; never compared.")]
[assembly: SuppressMessage("NDepend", "ND1313:OverrideEqualsAndOperatorEqualsOnValueTypes", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiExtension+DisposableImGuiIndent", Justification = "Scope guard; never compared.")]
[assembly: SuppressMessage("NDepend", "ND1313:OverrideEqualsAndOperatorEqualsOnValueTypes", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor+PerfSampler", Justification = "Scope guard; never compared.")]
// The clipboard delegates are kept alive in mutable statics: [FixedAddressValueType] roots them so
// the function pointers handed to native ImGui stay valid, and they can only be created once an
// instance exists. The thread-static pair caches the per-thread sample collection.
[assembly: SuppressMessage("NDepend", "ND1901:AvoidNonReadOnlyStaticFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem._setClipboardFn", Justification = "GC root for a native function pointer; assigned when the system starts.")]
[assembly: SuppressMessage("NDepend", "ND1901:AvoidNonReadOnlyStaticFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem._getClipboardFn", Justification = "GC root for a native function pointer; assigned when the system starts.")]
[assembly: SuppressMessage("NDepend", "ND1901:AvoidNonReadOnlyStaticFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticCollection", Justification = "[ThreadStatic] cache; one value per thread, rewritten when the monitor changes.")]
[assembly: SuppressMessage("NDepend", "ND1901:AvoidNonReadOnlyStaticFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticMonitor", Justification = "Owner marker for the thread-static cache.")]
[assembly: SuppressMessage("NDepend", "ND1902:AvoidStaticFieldsWithAMutableFieldType", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticCollection", Justification = "[ThreadStatic] cache of a mutable per-thread collection; that is its purpose.")]
[assembly: SuppressMessage("NDepend", "ND1902:AvoidStaticFieldsWithAMutableFieldType", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticMonitor", Justification = "Owner marker for the thread-static cache.")]
[assembly: SuppressMessage("NDepend", "ND1211:DontAssignStaticFieldsFromInstanceMethods", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem._setClipboardFn", Justification = "The delegate closes over instance state and can only exist once the system does.")]
[assembly: SuppressMessage("NDepend", "ND1211:DontAssignStaticFieldsFromInstanceMethods", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem._getClipboardFn", Justification = "The delegate closes over instance state and can only exist once the system does.")]
[assembly: SuppressMessage("NDepend", "ND1211:DontAssignStaticFieldsFromInstanceMethods", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticCollection", Justification = "The per-thread cache is filled from the sampling call path.")]
[assembly: SuppressMessage("NDepend", "ND1211:DontAssignStaticFieldsFromInstanceMethods", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor._threadStaticMonitor", Justification = "The per-thread cache is filled from the sampling call path.")]
[assembly: SuppressMessage("NDepend", "ND1300:AvoidCustomDelegates", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem+SetClipboardDelegate", Justification = "Func/Action cannot carry [UnmanagedFunctionPointer(Cdecl)], required for the native ImGui callback.")]
[assembly: SuppressMessage("NDepend", "ND1300:AvoidCustomDelegates", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem+GetClipboardDelegate", Justification = "Func/Action cannot carry [UnmanagedFunctionPointer(Cdecl)], required for the native ImGui callback.")]
// Backend/system classes own their device objects and dependencies; splitting the fields apart
// would only scatter one renderer's state across several types.
[assembly: SuppressMessage("NDepend", "ND1002:AvoidTypesWithTooManyFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem", Justification = "Rendering backend: pipeline, buffers, shader, io and input references are its state.")]
[assembly: SuppressMessage("NDepend", "ND1002:AvoidTypesWithTooManyFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor", Justification = "Profiler window: graphs, per-thread samples and Stride profiler plumbing are its state.")]
[assembly: SuppressMessage("NDepend", "ND1107:AvoidAddingInstanceFieldsToATypeThatAlreadyHadManyInstanceFields", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiSystem", Scope = "deep", Justification = "See ND1002 above; the baseline comparison counts the texture-manager refactor as an addition.")]
[assembly: SuppressMessage("NDepend", "ND1004:AvoidMethodsWithTooManyParameters", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.ImGuiExtension", Scope = "deep", Justification = "PlotLines mirrors the native Dear ImGui signature parameter for parameter.")]
[assembly: SuppressMessage("NDepend", "ND1701:PotentiallyDeadMethods", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor+ThreadSampleCollection", Scope = "deep", Justification = "Instantiated through the generic new() constraint in PerfMonitorHelpers.Guaranteed, which static analysis cannot see.")]
[assembly: SuppressMessage("NDepend", "ND1207:NonStaticClassesShouldBeInstantiatedOrTurnedToStatic", Target = "Stride.CommunityToolkit.ImGui:Stride.CommunityToolkit.ImGui.DebugTools.PerfMonitor+ThreadSampleCollection", Justification = "Instantiated through the generic new() constraint in PerfMonitorHelpers.Guaranteed, which static analysis cannot see.")]
// --- DebugShapes: the tagged-union design -------------------------------------------------------
// Renderable and DebugRenderable are tagged unions: one constructor per shape kind, all payloads at
// the same FieldOffset. That is what lets a frame of debug shapes live in one flat list with no
// allocation per shape.
[assembly: SuppressMessage("NDepend", "ND1005:AvoidMethodsWithTooManyOverloads", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Renderable", Scope = "deep", Justification = "One constructor per shape kind is the tagged union's discriminator.")]
[assembly: SuppressMessage("NDepend", "ND1005:AvoidMethodsWithTooManyOverloads", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.DebugRenderable", Scope = "deep", Justification = "One constructor per shape kind is the tagged union's discriminator.")]
// SizeOfInst sums the nine overlapping payloads; because they share one FieldOffset the real value
// is only as large as the biggest of them. ImmediateDebugRenderObject is a genuinely wide render
// object, but exactly four of them exist (solid/wireframe x opaque/transparent).
[assembly: SuppressMessage("NDepend", "ND1309:InstancesSizeShouldntBeTooBig", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.Renderable", Justification = "Explicit-layout union: the payloads overlap, so the instance is the size of its largest member.")]
[assembly: SuppressMessage("NDepend", "ND1309:InstancesSizeShouldntBeTooBig", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.DebugRenderable", Justification = "Explicit-layout union: the payloads overlap, so the instance is the size of its largest member.")]
[assembly: SuppressMessage("NDepend", "ND1309:InstancesSizeShouldntBeTooBig", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.ImmediateDebugRenderObject", Justification = "Holds six per-shape counter structs; four instances exist for the whole system.")]
// The byte width is load-bearing: DebugPrimitiveType sits at FieldOffset(0) and the payloads start
// at FieldOffset(1), so widening the enum would either break the layout or pad every queued shape.
[assembly: SuppressMessage("NDepend", "ND2206:EnumStorageShouldBeInt32", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.DebugPrimitiveType", Scope = "deep", Justification = "Packed into the tagged unions at FieldOffset(0); the payloads begin at byte 1.")]
[assembly: SuppressMessage("NDepend", "ND2206:EnumStorageShouldBeInt32", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.ImmediateDebugRenderSystem+DebugRenderableFlags", Scope = "deep", Justification = "Packed alongside DebugPrimitiveType in DebugRenderable's header bytes.")]
// The Draw* API mirrors Stride's own debug-draw shape: every parameter after the geometry has a
// default, so a call is normally DrawCapsule(position, height, radius). Folding them into an options
// object would make the common call longer, not shorter.
[assembly: SuppressMessage("NDepend", "ND1004:AvoidMethodsWithTooManyParameters", Target = "Stride.CommunityToolkit.DebugShapes:Stride.CommunityToolkit.DebugShapes.Code.ImmediateDebugRenderSystem", Scope = "deep", Justification = "Debug-draw API: geometry first, then all-defaulted color/duration/depthTest/solid.")]
// --- Charts -------------------------------------------------------------------------------
[assembly: SuppressMessage("NDepend", "ND1204:OverridesOfMethodShouldCallBaseMethod", Target = "Stride.CommunityToolkit.Charts:Stride.CommunityToolkit.Charts.ChartTrajectory.ReleaseResources()", Justification = "Replace, not refine, by design: the trajectory's buffers are owned and disposed by its GrowingPolyline; calling base would double-release them.")]
[assembly: SuppressMessage("NDepend", "ND2020:AvoidVariousCapitalizationsForMethodName", Target = "Stride.CommunityToolkit.Charts:Stride.CommunityToolkit.Charts.Chart.get_Game()", Justification = "Collides only with the F# examples' lowercase 'game' bindings; each language follows its own convention, like the entry-point entries above.")]
[assembly: SuppressMessage("NDepend", "ND1004:AvoidMethodsWithTooManyParameters", Target = "Stride.CommunityToolkit.Charts:Stride.CommunityToolkit.Charts.Chart.PlotParametric(Func<Single,Vector3>,Single,Single,Nullable<Color>,String,Int32,Boolean,ChartSeriesStyle)", Justification = "Every parameter past the curve itself is optional and named at the call site - colour, name, samples, closed, style. The alternative is an options object per call, which the API review removed on purpose because it forced callers to copy chart defaults by hand.")]
[assembly: SuppressMessage("NDepend", "ND1000:AvoidTypesTooBig", Target = "Stride.CommunityToolkit.Charts:Stride.CommunityToolkit.Charts.Chart", Justification = "The public facade over the chart's parts, which are already separate types: ChartScaffold (axes, ticks, labels, titles), ChartLegend, ChartGrid, ChartCursor and the ChartSeries family. What is left is one entry point per chart feature - Plot, AddLine, AddArea, AddMarkers and friends - averaging around fifteen statements each, plus the series pipeline they share.")]
[assembly: SuppressMessage("NDepend", "ND1001:AvoidTypesWithTooManyMethods", Target = "Stride.CommunityToolkit.Charts:Stride.CommunityToolkit.Charts.Chart", Justification = "Same facade as ND1000 above: the method count is the chart API's surface - overloads for plotting, adding and removing series - not accumulated responsibility.")]

// --- Box2D: the simulation facade ---
[assembly: SuppressMessage("NDepend", "ND1001:AvoidTypesWithTooManyMethods", Target = "Stride.CommunityToolkit.Box2D:Stride.CommunityToolkit.Box2D.Box2DSimulation", Justification = "The public facade over world, bridge, queries and events - the Box2D counterpart of BepuSimulation; its methods are one-line delegations to those parts.")]
[assembly: SuppressMessage("NDepend", "ND1207:NonStaticClassesShouldBeInstantiatedOrTurnedToStatic", Target = "Stride.CommunityToolkit.Box2D:Stride.CommunityToolkit.Box2D.Box2DCollisionMatrix", Justification = "Library API instantiated by consumers; nothing in the toolkit itself needs one yet.")]
[assembly: SuppressMessage("NDepend", "ND2500:DontCreateThreadsExplicitly", Target = "Stride.CommunityToolkit.Box2D:Stride.CommunityToolkit.Box2D.Box2DTaskScheduler..ctor(Int32)", Justification = "Deliberate: Box2D requires each concurrently running task callback to hold a distinct worker index, which dedicated threads guarantee structurally; the workers also park in a blocking dequeue for the world lifetime, which thread-pool threads must never do.")]
[assembly: SuppressMessage("NDepend", "ND2300:CollectionPropertiesShouldBeReadOnly", Target = "Stride.CommunityToolkit.Shapes:Stride.CommunityToolkit.Shapes.ShapeComponent.Vertices", Justification = "A runtime-swappable shape outline is the point of the component; the next frame draws whatever array is assigned.")]

// --- Examples.Core: one set of sources compiled into both launchers -------------------------
// Constants/Levels/ExampleManifest/ManifestExample/ExampleEntry/ManifestLoader live in the console
// runner and are <Compile Include Link=".."> into the Avalonia launcher. That is a deliberate,
// documented choice - see the comment on the linked ItemGroup in
// Stride.CommunityToolkit.Examples.Launcher.csproj: both launchers are single-project tools and a
// third project to hold six small types would cost more than it saves. The two rules below are the
// unavoidable price of it, and neither describes a real defect: it is one source file compiled
// twice, not two divergent copies.
[assembly: SuppressMessage("NDepend", "ND2101:AvoidDuplicatingATypeDefinitionAcrossAssemblies", Target = "Stride.CommunityToolkit.Examples:Stride.CommunityToolkit.Examples.Core", Scope = "deep", Justification = "Shared manifest-reading sources linked into both launchers; one file, two compilations.")]
[assembly: SuppressMessage("NDepend", "ND2100:AvoidReferencingSourceFileOutOfTheProjectDirectory", Target = "Stride.CommunityToolkit.Examples.Launcher:Stride.CommunityToolkit.Examples.Core", Scope = "deep", Justification = "The linked ItemGroup is the point; the files are owned by Stride.CommunityToolkit.Examples next door.")]

// --- Example10: the Bepu and Bullet twins -----------------------------------------------------
// The two Example10 projects are the same scene on two physics engines, kept side by side so the
// difference between them is the diff. They deliberately share namespace and type names.
[assembly: SuppressMessage("NDepend", "ND2101:AvoidDuplicatingATypeDefinitionAcrossAssemblies", Target = "Example10_StrideUI_DragAndDrop:Example10_StrideUI_DragAndDrop", Scope = "deep", Justification = "Bepu twin of Example10_StrideUI_DragAndDrop_BulletPhysics; same scene, different engine, on purpose.")]
[assembly: SuppressMessage("NDepend", "ND2101:AvoidDuplicatingATypeDefinitionAcrossAssemblies", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:Example10_StrideUI_DragAndDrop", Scope = "deep", Justification = "Bullet twin of Example10_StrideUI_DragAndDrop; same scene, different engine, on purpose.")]
// Scope="deep" on a namespace covers its own types, not those of a child namespace, so the .UI
// namespace needs its own pair of entries.
[assembly: SuppressMessage("NDepend", "ND2101:AvoidDuplicatingATypeDefinitionAcrossAssemblies", Target = "Example10_StrideUI_DragAndDrop:Example10_StrideUI_DragAndDrop.UI", Scope = "deep", Justification = "Bepu twin of Example10_StrideUI_DragAndDrop_BulletPhysics; same scene, different engine, on purpose.")]
[assembly: SuppressMessage("NDepend", "ND2101:AvoidDuplicatingATypeDefinitionAcrossAssemblies", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:Example10_StrideUI_DragAndDrop.UI", Scope = "deep", Justification = "Bullet twin of Example10_StrideUI_DragAndDrop; same scene, different engine, on purpose.")]
[assembly: SuppressMessage("NDepend", "ND3101:DontUseSystemRandomForSecurityPurposes", Target = "Example10_StrideUI_DragAndDrop:Example10_StrideUI_DragAndDrop.PrimitiveGenerator", Scope = "deep", Justification = "Scatters cubes around the scene; nothing security-related, same as Helpers.VectorHelper above.")]
[assembly: SuppressMessage("NDepend", "ND3101:DontUseSystemRandomForSecurityPurposes", Target = "Example10_StrideUI_DragAndDrop_BulletPhysics:Example10_StrideUI_DragAndDrop.PrimitiveGenerator", Scope = "deep", Justification = "Scatters cubes around the scene; nothing security-related, same as Helpers.VectorHelper above.")]

// --- Launcher: the Avalonia entry-point contract -----------------------------------------------
// Avalonia's project template declares BuildAvaloniaApp as a public static method on an internal
// Program, and the XAML previewer finds it by name through reflection. Narrowing it to internal or
// private is what both rules ask for and would change nothing for any caller - Program is already
// internal - but it is exactly the shape the tooling looks for, so it stays as the template has it.
[assembly: SuppressMessage("NDepend", "ND1800:MethodsThatCouldHaveALowerVisibility", Target = "Stride.CommunityToolkit.Examples.Launcher:Stride.CommunityToolkit.Examples.Launcher.Program.BuildAvaloniaApp()", Justification = "Avalonia entry-point contract; found by the XAML previewer through reflection.")]
[assembly: SuppressMessage("NDepend", "ND1807:AvoidPublicMethodsNotPubliclyVisible", Target = "Stride.CommunityToolkit.Examples.Launcher:Stride.CommunityToolkit.Examples.Launcher.Program.BuildAvaloniaApp()", Justification = "Avalonia entry-point contract; found by the XAML previewer through reflection.")]

// --- ImGuiNet: the same two facts already recorded for the ImGui package -----------------------
[assembly: SuppressMessage("NDepend", "ND1002:AvoidTypesWithTooManyFields", Target = "Stride.CommunityToolkit.ImGuiNet:Stride.CommunityToolkit.ImGuiNet.ImGuiNetSystem", Justification = "Rendering backend: pipeline, buffers, shader, context, DPI and input references are its state - same as ImGuiSystem above.")]
[assembly: SuppressMessage("NDepend", "ND1004:AvoidMethodsWithTooManyParameters", Target = "Stride.CommunityToolkit.ImGuiNet:Stride.CommunityToolkit.ImGuiNet.ImGuiNetExtensions.DrawText(ImGuiNetSystem,Int32,Int32,String,Byte,Byte,Byte,Byte)", Justification = "Byte-per-channel colour mirrors the Box2D.NET draw API this overload exists to match; the Vector4 overload on ImGuiNetSystem.DrawString is the shorter path.")]
// ImGuiNetSystem is 206 statements against a 200 threshold, and gained two instance fields against
// the baseline. Splitting RenderImGuiDrawData and Update into named steps - which is what cleared the
// two "even more complex / even larger" regressions on them - is what carried it over: extraction
// trades branches inside a method for a handful of call statements on the type. That is the better
// shape to read, so it stays. The honest fix for the remaining size is to give the draw-data
// rendering and the font atlas their own types, the way the ImGui package already did with
// ImGuiTextureManager and ImGuiNetTextOverlay; the font atlas owns _fontTexture, which the renderer
// and Destroy both use, so that is a real refactor of a graphics path and wants a run of
// Example11_ImGuiNet behind it rather than a quiet edit.
[assembly: SuppressMessage("NDepend", "ND1000:AvoidTypesTooBig", Target = "Stride.CommunityToolkit.ImGuiNet:Stride.CommunityToolkit.ImGuiNet.ImGuiNetSystem", Justification = "Rendering backend, 6 statements over the threshold; see the note above on the pending renderer/font-atlas extraction.")]
[assembly: SuppressMessage("NDepend", "ND1107:AvoidAddingInstanceFieldsToATypeThatAlreadyHadManyInstanceFields", Target = "Stride.CommunityToolkit.ImGuiNet:Stride.CommunityToolkit.ImGuiNet.ImGuiNetSystem", Scope = "deep", Justification = "See ND1002 above; the baseline comparison counts the DPI/font-scaling state as an addition - same situation as ImGuiSystem.")]